version: 2
updates:
  - package-ecosystem: npm
    directory: /packages/analytics
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - analytics

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
